development:
  adapter: postgresql
  encoding: unicode
  database: canvas_dev
  pool: 5
  username: basedgod
  password: 
  min_messages: WARNING

test:
  adapter: postgresql
  encoding: unicode
  database: canvas_test
  pool: 5
  username: basedgod
  password: 